export const abbreviations = [
  { term: "PPE", meaning: "Personal Protective Equipment" },
  { term: "WPR", meaning: "Work Permit Receiver" },
  { term: "PTW", meaning: "Permit To Work" },
  { term: "JSA", meaning: "Job Safety Analysis" },
  { term: "SDS", meaning: "Safety Data Sheet" },
  { term: "LOTO", meaning: "Lockout / Tagout" },
  { term: "SCBA", meaning: "Self-Contained Breathing Apparatus" },
  { term: "MEWP", meaning: "Mobile Elevated Work Platform" },
  { term: "ERT", meaning: "Emergency Response Team" },
  { term: "CBT", meaning: "Computer-Based Test" },
  { term: "H2S", meaning: "Hydrogen Sulfide (toxic gas)" },
  { term: "LEL", meaning: "Lower Explosive Limit" },
  { term: "HSE", meaning: "Health, Safety and Environment" },
  { term: "CO2", meaning: "Carbon Dioxide (fire extinguishing agent / gas hazard)" },
  { term: "O2", meaning: "Oxygen" },
  { term: "FR", meaning: "Fire Retardant / Flame Resistant (clothing)" },
  { term: "SIMOPS", meaning: "Simultaneous Operations" },
  { term: "MSDS", meaning: "Material Safety Data Sheet (older term for SDS)" },
  { term: "NORM", meaning: "Naturally Occurring Radioactive Material" },
  { term: "RPE", meaning: "Respiratory Protective Equipment" },
]

export const permitGuide = [
  { job: "Welding, cutting, grinding, brazing", permit: "Hot Work Permit" },
  { job: "General maintenance with no fire/confined risk", permit: "Cold Work Permit" },
  { job: "Entering tanks, vessels, pits, sewers", permit: "Confined Space Entry Permit" },
  { job: "Digging, trenching, ground-breaking", permit: "Excavation Permit" },
  { job: "Working on or isolating electrical circuits", permit: "Electrical Isolation Permit (LOTO)" },
  { job: "Crane operations, mechanical lifting", permit: "Lifting Permit" },
  { job: "Scaffold erection, dismantling, or use", permit: "Scaffold / Working at Height Permit" },
  { job: "Ladders, MEWPs, roof access, elevated work", permit: "Working at Height Permit" },
  { job: "Radioactive sources, radiography", permit: "Radiography Permit" },
  { job: "Breaking containment on a process line", permit: "Line-Breaking / Isolation Permit" },
  { job: "Diving or underwater operations", permit: "Diving Operations Permit" },
  { job: "Blasting or use of explosives", permit: "Explosives / Blasting Permit" },
  { job: "Vehicle entry into a hazardous process area", permit: "Vehicle Entry Permit" },
  { job: "Temporary bypass of a safety system", permit: "Impairment / Bypass Permit" },
  { job: "Pressure testing of pipelines or vessels", permit: "Pressure Test Permit" },
]

export const safetyItems = [
  "Hard hat / safety helmet",
  "Safety glasses / goggles",
  "Face shield",
  "Hearing protection (earplugs/earmuffs)",
  "Respirator / dust mask / SCBA",
  "Safety gloves (matched to hazard type)",
  "Safety shoes / steel-toe boots",
  "Coveralls / FR clothing",
  "High-visibility vest",
  "Fall-arrest harness and lanyard",
  "Gas detector (portable, calibrated)",
  "Fire extinguisher (correct class for the hazard)",
  "Fire blanket",
  "Barricades / warning tape / signage",
  "First aid kit",
  "Emergency shower and eyewash station",
  "Spill kit",
  "Two-way radio / communication device",
  "Rescue/retrieval equipment (tripod, winch, lifeline)",
  "Lockout/tagout locks and tags",
]
