export const abbreviations = [
  { term: "PPE", meaning: "Personal Protective Equipment" },
  { term: "WPR", meaning: "Work Permit Receiver" },
  { term: "PTW", meaning: "Permit To Work" },
  { term: "JSA", meaning: "Job Safety Analysis" },
  { term: "SDS", meaning: "Safety Data Sheet" },
  { term: "LOTO", meaning: "Lockout / Tagout" },
  { term: "SCBA", meaning: "Self-Contained Breathing Apparatus" },
  { term: "MEWP", meaning: "Mobile Elevated Work Platform" },
  { term: "ERT", meaning: "Emergency Response Team" },
  { term: "CBT", meaning: "Computer-Based Test" },
  { term: "H2S", meaning: "Hydrogen Sulfide (toxic gas)" },
  { term: "LEL", meaning: "Lower Explosive Limit" },
  { term: "HSE", meaning: "Health, Safety and Environment" },
  { term: "CO2", meaning: "Carbon Dioxide (fire extinguishing agent / gas hazard)" },
  { term: "O2", meaning: "Oxygen" },
  { term: "FR", meaning: "Fire Retardant / Flame Resistant (clothing)" },
  { term: "SIMOPS", meaning: "Simultaneous Operations" },
  { term: "MSDS", meaning: "Material Safety Data Sheet (older term for SDS)" },
  { term: "NORM", meaning: "Naturally Occurring Radioactive Material" },
  { term: "RPE", meaning: "Respiratory Protective Equipment" },
]

export const permitGuide = [
  { job: "Welding, cutting, grinding, brazing", permit: "Hot Work Permit" },
  { job: "General maintenance with no fire/confined risk", permit: "Cold Work Permit" },
  { job: "Entering tanks, vessels, pits, sewers", permit: "Confined Space Entry Permit" },
  { job: "Digging, trenching, ground-breaking", permit: "Excavation Permit" },
  { job: "Working on or isolating electrical circuits", permit: "Electrical Isolation Permit (LOTO)" },
  { job: "Crane operations, mechanical lifting", permit: "Lifting Permit" },
  { job: "Scaffold erection, dismantling, or use", permit: "Scaffold / Working at Height Permit" },
  { job: "Ladders, MEWPs, roof access, elevated work", permit: "Working at Height Permit" },
  { job: "Radioactive sources, radiography", permit: "Radiography Permit" },
  { job: "Breaking containment on a process line", permit: "Line-Breaking / Isolation Permit" },
  { job: "Diving or underwater operations", permit: "Diving Operations Permit" },
  { job: "Blasting or use of explosives", permit: "Explosives / Blasting Permit" },
  { job: "Vehicle entry into a hazardous process area", permit: "Vehicle Entry Permit" },
  { job: "Temporary bypass of a safety system", permit: "Impairment / Bypass Permit" },
  { job: "Pressure testing of pipelines or vessels", permit: "Pressure Test Permit" },
]

export const colorCoding = [
  { color: "Red", hex: "#c0392b", permits: ["Hot Work Permit"] },
  { color: "Yellow", hex: "#d4a017", permits: ["Cold Work Permit", "General/Routine Work Permit"] },
  { color: "Blue", hex: "#1a6fb0", permits: ["Electrical Isolation Permit (LOTO)"] },
  { color: "Green", hex: "#2f9e58", permits: ["Confined Space Entry Permit"] },
  { color: "White", hex: "#888888", permits: ["Excavation Permit"] },
  { color: "Grey", hex: "#607080", permits: ["Radiography Permit"] },
  { color: "Orange", hex: "#d2691e", permits: ["Working at Height Permit", "Lifting Permit", "Scaffold Permit"] },
  { color: "Pink", hex: "#c2185b", permits: ["Vehicle Entry Permit", "Special/High-Risk Permit"] },
]

export const safetyItems = [
  { icon: "⛑️", name: "Hard hat / safety helmet", desc: "Protects the head from falling objects and impacts." },
  { icon: "🥽", name: "Safety glasses / goggles", desc: "Shields eyes from debris, dust, and chemical splashes." },
  { icon: "😷", name: "Face shield", desc: "Extra protection for the full face against splashes or flying particles." },
  { icon: "🎧", name: "Hearing protection (earplugs/earmuffs)", desc: "Reduces exposure to harmful noise levels." },
  { icon: "😮‍💨", name: "Respirator / dust mask / SCBA", desc: "Protects the lungs from dust, gases, or oxygen-deficient air." },
  { icon: "🧤", name: "Safety gloves (matched to hazard type)", desc: "Protects hands from cuts, chemicals, or heat depending on type." },
  { icon: "🥾", name: "Safety shoes / steel-toe boots", desc: "Protects feet from impact, punctures, and slips." },
  { icon: "🦺", name: "Coveralls / FR clothing", desc: "Flame-resistant body protection for hazardous work." },
  { icon: "🦺", name: "High-visibility vest", desc: "Makes workers easily seen around vehicles and machinery." },
  { icon: "🪢", name: "Fall-arrest harness and lanyard", desc: "Prevents falls when working at height." },
  { icon: "📟", name: "Gas detector (portable, calibrated)", desc: "Monitors oxygen, flammable, and toxic gas levels." },
  { icon: "🧯", name: "Fire extinguisher (correct class for the hazard)", desc: "Used to control small fires of a specific class." },
  { icon: "🔥", name: "Fire blanket", desc: "Smothers small fires or wraps around a person whose clothing is on fire." },
  { icon: "🚧", name: "Barricades / warning tape / signage", desc: "Warns and restricts entry into hazardous zones." },
  { icon: "🩹", name: "First aid kit", desc: "Basic supplies for treating minor injuries on site." },
  { icon: "🚿", name: "Emergency shower and eyewash station", desc: "Flushes chemicals from skin or eyes immediately after exposure." },
  { icon: "🧪", name: "Spill kit", desc: "Contains and cleans up chemical or oil spills safely." },
  { icon: "📻", name: "Two-way radio / communication device", desc: "Keeps workers and standby personnel in contact." },
  { icon: "🛟", name: "Rescue/retrieval equipment (tripod, winch, lifeline)", desc: "Used to rescue an entrant from a confined space quickly." },
  { icon: "🔒", name: "Lockout/tagout locks and tags", desc: "Physically isolates hazardous energy sources during maintenance." },
]
